### ISSUE TITLE
Won't work in Firefox: "SecurityError: The operation is insecure."

### ISSUE THREAD

**Issue by lolmaus** [tysonmatanich/elementQuery#10]
Hi!

Firefox 25.0.1.

elementQuery produces:

> SecurityError: The operation is insecure.
> http://localhost:4567/javascripts/vendor/elementQuery.js?body=1
> Line 19

It works in other browsers.

**Comment by lolmaus** [comment]
I've managed to locate the problem.

The error happens due to this issue: [Firefox not able to enumerate document.styleSheets[].cssRules[]](http://stackoverflow.com/questions/5323604/firefox-not-able-to-enumerate-document-stylesheets-cssrules) for cross-domain stylesheets.

When i comment out a Google Fonts stylesheet, elementQuery starts working in Firefox.

```
<link type="text/css" rel="stylesheet" media="screen" href="//fonts.googleapis.com/css?family=PT+Sans:400,700,400italic,700italic&amp;subset=latin,cyrillic-ext,latin-ext,cyrillic">
```

Please fix this.

**Comment by tysonmatanich** [comment]
Sorry, can't fix as it is the security model that some browsers chose. However, there is a workaround documented; please see "Expanded Support" section of the [related Smashing Magazine article](http://coding.smashingmagazine.com/2013/06/25/media-queries-are-not-the-answer-element-query-polyfill/).

**Comment by lolmaus** [comment]
Ain't it possible to make ElementQuery ignore external stylesheets? Make it optional maybe? Tell ElementQuery explicitly which stylesheets to parse?

The issue with Firefox is pretty huge.

**Comment by hellolindsay** [comment]
I have found a fix for this -- you can modify the elementQuery.js source code and add a line of code. External stylesheets still wont load, but they will fail elegantly without the error or it's side effects:
http://www.smashingmagazine.com/2013/06/25/media-queries-are-not-the-answer-element-query-polyfill/#comment-1221353

**Comment by lolmaus** [comment]
Thank you @hellolindsay.

PS Is there a maintained fork of this lib?

**Comment by jesseyangjincheng** [comment]
非常感谢！

**Comment by lolmaus** [comment]
> 非常感谢！

Всегда пожалуйста!
