### ISSUE TITLE
::before and ::after rules inside element query blocks cause Sizzle error

### ISSUE THREAD

**Issue by yogaraptor** [tysonmatanich/elementQuery#12]
https://gist.github.com/itsravenous/8320654

The sizzle error thrown:

`Uncaught Error: Syntax error, unrecognized expression: .menu li::after`

**Comment by yogaraptor** [comment]
Please ignore - must have been doing something wrong as I've got it working now.

**Comment by coutureJ** [comment]
Same problem here, 

Here's my code:

```
.modern:not(.we_not-responsive) &[max-width~="470px"]{
    background-image:none;
    padding:15px !important;
    &:before{
        display:none;
    }
}
```

The problem happen only if you put the "&:before or &:after" directly inside your elementQuery query.

If I create another div inside my element and I do something like this, It work flawlessly.:

```
.modern:not(.we_not-responsive) &[max-width~="470px"]{
    background-image:none;
    padding:15px !important;
    >div:before{
        display:none;
    }
}
```

Any idea?
