### ISSUE TITLE
Preprocessor

### ISSUE THREAD

**Issue by SamHasler** [tysonmatanich/elementQuery#18]
Would it be possible to have a preprocessor that would take a css file with element queries in it, and output: a "pure" css file with classes instead of the queries, and a js file that contains the element queries and the new css classes they map to?

This would allow maintaining the queries in css whilst delivering pure CSS to the client and avoiding processing the css files in js on the client.

**Comment by tysonmatanich** [comment]
Would be awesome but don't have the time to invest in writing a preprocessor. The current solution works but would love to see someone write a preprocessor... ;) ;)
