### ISSUE TITLE
Doent work in firefox

### ISSUE THREAD

**Issue by michaelDotco2** [tysonmatanich/elementQuery#19]
This doesn't work in firefox.

I have this error

SecurityError: The operation is insecure.
if (styleSheet[cssRules] && styleSheet[cssRules].length > 0) {

but even when changed to 

if (styleSheet.lenght >0) {
The query doesn't work.

**Comment by stendelis** [comment]
I have same isue, you can fix it?

**Comment by tysonmatanich** [comment]
This is a known issue that cannot be fixed (only worked around) and is a security restriction imposed by your browser.

Please see https://github.com/tysonmatanich/elementQuery#selector-registration

"The prod branch requires the selector information to be declared in JavaScript, which avoids the cross-domain file issue and the time required to parse the style sheets."

More on that here http://www.smashingmagazine.com/2013/06/25/media-queries-are-not-the-answer-element-query-polyfill/ under "Expanded Support" section.
