### ISSUE TITLE
Not firing until resize

### ISSUE THREAD

**Issue by gorkamolero** [tysonmatanich/elementQuery#21]
Hey guys!

I can't get the plugin to style the element until the window resizes, I'm using Chrome 37.

Anybody else having this issue?

**Comment by tysonmatanich** [comment]
Works fine for me in Chrome 37. Might be something else on your page preventing it from working. I would recommend creating a simplified version of your page that you can test with. Also compare to the demo links (such as http://codepen.io/tysonmatanich/pen/wramd). It should run on resize, dom ready, and load.

You can also call it yourself via `elementQuery()`
