### ISSUE TITLE
Firefox situation

### ISSUE THREAD

**Issue by stendelis** [tysonmatanich/elementQuery#22]
Hi,

Sorry for my bad english.

This script is great.

I have a situation, in Chrome run OK, but in Firefox not.

See the demo. You see an error in my code?

http://www.accuweatherglobal.com/AWG-Widget/test/widget/v.1.0.0/test.html

**Comment by tysonmatanich** [comment]
Sounds related to https://github.com/tysonmatanich/elementQuery/issues/19
