### ISSUE TITLE
Bower support

### ISSUE THREAD

**Issue by dodozhang21** [tysonmatanich/elementQuery#24]
Could you make this available via bower? We would love to use it without having to check the script into our code base.

Thank you!

**Comment by jarrodpayne** [comment]
Bower understands GitHub. Perhaps you could do

```
"elementQuery": "tysonmatanich/elementQuery"
```

Or,

```
"elementQuery": "https://github.com/tysonmatanich/elementQuery/archive/master.zip"
```

Or, any other variation of that kind of thing.

**Comment by dodozhang21** [comment]
ok this works for me

"elementQuery": "https://github.com/tysonmatanich/elementQuery.git#f3e328c7070e5d8e11682979092a5c06925c6ad3"

**Comment by tysonmatanich** [comment]
Awesome, thanks for the suggestion @jpdesigndev.

**Comment by dandv** [comment]
Duplicate of #11. However, looks like this project is no longer maintained.
