### ISSUE TITLE
Add support for stylesheets loaded with an @import

### ISSUE THREAD

**Issue by Sam152** [tysonmatanich/elementQuery#6]
Thanks for the great library. I think it would be a good advancement to support styles loaded with "@import".

**Comment by tysonmatanich** [comment]
Unlikely to fix as I frown on `@import` as the CSS should use bundling instead of making multiple requests.

**Comment by CodySchneider** [comment]
Fixed this because our Drupal dev environment uses @import... prod aggregates of course, but fixed it for myself and thought I'd share.

**Comment by Sam152** [comment]
We're using Drupal with the same problem. Where can I find the code?

**Comment by CodySchneider** [comment]
There's an open pull request or you can check out my forked version.
