### ISSUE TITLE
Hidden elements don't always respect their query properties. 

### ISSUE THREAD

**Issue by sachasayan** [tysonmatanich/elementQuery#7]
Anything with display:none won't properly respect queries on page load -- a window-resize is then required for these objects to 'snap' into their proper dimensions/properties. 

Perhaps a performant way around this problem would be to expose a refresh function to developers to be able to trigger the plugin manually?

**Comment by getvega** [comment]
Hi did you manage to work around this issue ?

**Comment by tysonmatanich** [comment]
Calling `elementQuery()` should do a refresh.
